version: '2'
services:
  # This is your service: adjust the command and add environments statements
  elasticsearch:
    image: elasticsearch
    command: bash -xc "usermod -u 1000 elasticsearch; gosu elasticsearch elasticsearch"
    volumes:
      - ${PWD}/esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  logstash:
    image: logstash
    command: logstash -f /etc/logstash/conf.d --debug
    depends_on:
      - elasticsearch
    volumes:
      - /var/log/docker.log:/var/log/docker.log:ro
      - $PWD/logstash/conf.d:/etc/logstash/conf.d:ro


# vim: ft=yaml:
